using System.Collections.Generic;

namespace NM.Core.Reconciliation.Models
{
    /// <summary>
    /// A suggested custom property write for a SolidWorks model.
    /// Generated by PropertySuggestionService from reconciliation results.
    /// Presented to the user in the UI wizard for approval before writing.
    /// </summary>
    public sealed class PropertySuggestion
    {
        /// <summary>SolidWorks custom property name (e.g., "Description", "F220_Note").</summary>
        public string PropertyName { get; set; }

        /// <summary>Suggested value to write.</summary>
        public string Value { get; set; }

        /// <summary>Current value in the model (empty if not set).</summary>
        public string CurrentValue { get; set; }

        /// <summary>Where this suggestion came from.</summary>
        public SuggestionSource Source { get; set; }

        /// <summary>Category for grouping in the UI.</summary>
        public PropertyCategory Category { get; set; }

        /// <summary>Confidence (0.0 - 1.0).</summary>
        public double Confidence { get; set; }

        /// <summary>Human-readable explanation of why this is suggested.</summary>
        public string Reason { get; set; }

        /// <summary>True if CurrentValue is empty/missing (gap fill vs override).</summary>
        public bool IsGapFill => string.IsNullOrEmpty(CurrentValue);

        /// <summary>True if the suggestion would change an existing value.</summary>
        public bool IsOverride => !string.IsNullOrEmpty(CurrentValue) &&
                                   !string.Equals(CurrentValue, Value, System.StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// An assembly operation slot — represents one row in the
    /// assembly custom property tab builder's free-form operation list.
    /// </summary>
    public sealed class AssemblyOperationSuggestion
    {
        /// <summary>Suggested operation number (10, 20, 30, etc.).</summary>
        public int OpNumber { get; set; }

        /// <summary>Work center code (e.g., "KIT", "F400", "N140").</summary>
        public string WorkCenter { get; set; }

        /// <summary>Setup time in minutes.</summary>
        public double Setup_min { get; set; }

        /// <summary>Run time in minutes.</summary>
        public double Run_min { get; set; }

        /// <summary>Routing note text.</summary>
        public string RoutingNote { get; set; }

        /// <summary>Source drawing note that generated this suggestion.</summary>
        public string SourceNote { get; set; }

        /// <summary>Confidence (0.0 - 1.0).</summary>
        public double Confidence { get; set; }

        /// <summary>
        /// Returns the custom property names for this operation slot.
        /// Assembly operations use a generic OP##_WC, OP##_S, OP##_R, OP##_RN pattern.
        /// </summary>
        public Dictionary<string, string> ToProperties()
        {
            string prefix = $"OP{OpNumber}";
            var props = new Dictionary<string, string>();

            if (!string.IsNullOrEmpty(WorkCenter))
                props[$"{prefix}_WC"] = WorkCenter;
            if (Setup_min > 0)
                props[$"{prefix}_S"] = Setup_min.ToString("0.####", System.Globalization.CultureInfo.InvariantCulture);
            if (Run_min > 0)
                props[$"{prefix}_R"] = Run_min.ToString("0.####", System.Globalization.CultureInfo.InvariantCulture);
            if (!string.IsNullOrEmpty(RoutingNote))
                props[$"{prefix}_RN"] = RoutingNote;

            return props;
        }
    }

    public enum SuggestionSource
    {
        DrawingTitleBlock,
        DrawingNote,
        DrawingGdT,
        AiVision,
        Reconciliation
    }

    public enum PropertyCategory
    {
        Identity,        // PartNumber, Description, Revision
        Material,        // Material, Finish, OptiMaterial
        Routing,         // Operation WC, setup, run, notes
        Geometry,        // Thickness, dimensions
        Quality          // GD&T, inspection requirements
    }
}
